### ISSUE TITLE
hade build all报错Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead

### ISSUE THREAD

**Issue by stonecool** [gohade/hade#9]
- 报错
  ```
  $ hade build all
  =============  前端编译失败 ============
  
  > hade@1.0.0 build /home/test/hade_example
  > node build/build.js
  
  /home/test/hade_example/node_modules/webpack/lib/webpack.js:165
                          throw new RemovedPluginError(errorMessage);
                          ^
  
  Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
      at Object.get [as CommonsChunkPlugin] (/home/test/hade_example/node_modules/webpack/lib/webpack.js:165:10)
      at Object.<anonymous> (/home/test/hade_example/build/webpack.prod.conf.js:86:26)
      at Module._compile (module.js:660:30)
      at Object.Module._extensions..js (module.js:671:10)
      at Module.load (module.js:573:32)
      at tryModuleLoad (module.js:513:12)
      at Function.Module._load (module.js:505:3)
      at Module.require (module.js:604:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/home/test/hade_example/build/build.js:12:23)
      at Module._compile (module.js:660:30)
      at Object.Module._extensions..js (module.js:671:10)
      at Module.load (module.js:573:32)
      at tryModuleLoad (module.js:513:12)
      at Function.Module._load (module.js:505:3)
      at Function.Module.runMain (module.js:701:10)
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! hade@1.0.0 build: `node build/build.js`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the hade@1.0.0 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/.npm/_logs/2023-03-07T02_30_53_322Z-debug.log
  
  =============  前端编译失败 ============
  Error: exit status 1
  Usage:
    hade build all [flags]
  
  Flags:
    -h, --help   help for all
  ```

- 环境：
  ```
  $ go version
  go version go1.19.2 linux/amd64
  $ npm -version
  5.5.1
  ```

网上查了些资料，是webpack版本的问题，尝试了几种修改，都没成功

**Comment by stonecool** [comment]
#### 1. Current issue solved
- webpack.base.conf.js
  ```Bash
  $ diff -uNr webpack.base.conf.js.bak webpack.base.conf.js
  --- webpack.base.conf.js.bak    2023-03-07 10:20:34.474413605 +0800
  +++ webpack.base.conf.js        2023-03-08 08:39:46.786226474 +0800
  @@ -38,6 +38,17 @@
         '@': resolve('src'),
       }
     },
  +  optimization: {
  +    splitChunks: {
  +      cacheGroups: {
  +        commons: {
  +          name: 'commons',
  +          chunks: 'initial',
  +          minChunks: 2
  +        }
  +      }
  +    }
  +  },
     module: {
       rules: [
         ...(config.dev.useEslint ? [createLintingRule()] : []),
  ```

- webpack.prod.conf.js
  ```Bash
  $ diff -uNr webpack.prod.conf.js.bak webpack.prod.conf.js
  --- webpack.prod.conf.js.bak    2023-03-07 10:29:44.149851937 +0800
  +++ webpack.prod.conf.js        2023-03-08 08:35:38.164239113 +0800
  @@ -83,34 +83,34 @@
       // enable scope hoisting
       new webpack.optimize.ModuleConcatenationPlugin(),
       // split vendor js into its own file
  -    new webpack.optimize.CommonsChunkPlugin({
  -      name: 'vendor',
  -      minChunks (module) {
  -        // any required modules inside node_modules are extracted to vendor
  -        return (
  -          module.resource &&
  -          /\.js$/.test(module.resource) &&
  -          module.resource.indexOf(
  -            path.join(__dirname, '../node_modules')
  -          ) === 0
  -        )
  -      }
  -    }),
  +//    new webpack.optimize.CommonsChunkPlugin({
  +//      name: 'vendor',
  +//      minChunks (module) {
  +//        // any required modules inside node_modules are extracted to vendor
  +//        return (
  +//          module.resource &&
  +//          /\.js$/.test(module.resource) &&
  +//          module.resource.indexOf(
  +//            path.join(__dirname, '../node_modules')
  +//          ) === 0
  +//        )
  +//      }
  +//    }),
       // extract webpack runtime and module manifest to its own file in order to
       // prevent vendor hash from being updated whenever app bundle is updated
  -    new webpack.optimize.CommonsChunkPlugin({
  -      name: 'manifest',
  -      minChunks: Infinity
  -    }),
  +//    new webpack.optimize.CommonsChunkPlugin({
  +//      name: 'manifest',
  +//      minChunks: Infinity
  +//    }),
       // This instance extracts shared chunks from code splitted chunks and bundles them
       // in a separate chunk, similar to the vendor chunk
       // see: https://webpack.js.org/plugins/commons-chunk-plugin/#extra-async-commons-chunk
  -    new webpack.optimize.CommonsChunkPlugin({
  -      name: 'app',
  -      async: 'vendor-async',
  -      children: true,
  -      minChunks: 3
  -    }),
  +//    new webpack.optimize.CommonsChunkPlugin({
  +//      name: 'app',
  +//      async: 'vendor-async',
  +//      children: true,
  +//      minChunks: 3
  +//    }),

       // copy custom static assets
       new CopyWebpackPlugin([
  ```

#### 2. Other issues arise and solved

```Bash
TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /home/xxx/hade_example/node_modules/html-webpack-plugin/lib/compiler.js:81:51
    at compile (/home/xxx/hade_example/node_modules/webpack/lib/Compiler.js:242:11)
    at hooks.afterCompile.callAsync.err (/home/xxx/hade_example/node_modules/webpack/lib/Compiler.js:487:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/hade_example/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/xxx/hade_example/node_modules/webpack/lib/Compiler.js:484:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/hade_example/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/home/xxx/hade_example/node_modules/webpack/lib/Compilation.js:966:35)
    at _err0 (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at LastCallWebpackPlugin.process (/home/xxx/hade_example/node_modules/last-call-webpack-plugin/index.js:126:12)
    at /home/xxx/hade_example/node_modules/last-call-webpack-plugin/index.js:197:12
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/hade_example/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/home/xxx/hade_example/node_modules/webpack/lib/Compilation.js:957:32)
    at _err2 (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)

$ npm i html-webpack-plugin@4.4.0 --save-dev

#############################

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/home/xxx/hade_example/node_modules/webpack/lib/Chunk.js:712:9)
    at /home/xxx/hade_example/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /home/xxx/hade_example/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at AsyncSeriesHook.lazyCompileHook (/home/xxx/hade_example/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/xxx/hade_example/node_modules/webpack/lib/Compilation.js:890:27)
    at hooks.make.callAsync.err (/home/xxx/hade_example/node_modules/webpack/lib/Compiler.js:481:17)
    at _done (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (/home/xxx/hade_example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (/home/xxx/hade_example/node_modules/webpack/lib/Compilation.js:758:12)
    at processModuleDependencies.err (/home/xxx/hade_example/node_modules/webpack/lib/Compilation.js:697:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)

$ npm install extract-text-webpack-plugin@next --save-dev

#############################

ERROR in ./src/main.js
Module build failed: TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (/home/xxx/hade_example/node_modules/eslint-loader/index.js:148:18)

  Build failed with errors.

$ npm install eslint-loader@2.1.2 --save-dev

#############################

ERROR in ./src/App.vue
Module build failed: TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/xxx/hade_example/node_modules/vue-loader/lib/loader.js:61:18)
 @ ./src/main.js 4:0-24 13:21-24

ERROR in ./src/components/HelloWorld.vue
Module build failed: TypeError: Cannot read property 'vue' of undefined
    at Object.module.exports (/home/xxx/hade_example/node_modules/vue-loader/lib/loader.js:61:18)
 @ ./src/router/index.js 3:0-49 11:15-25
 @ ./src/main.js

$ npm install vue-loader@14.2.2 --save-dev
```

compile successfully
